pipelines:
  - name: ionic_app
    steps:
      - name: build_ionic_app
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: node/client/.
          inputResources:
            - name: ionic_app_repo
          integrations:
            - name: this_artifactory
        execution:
          onComplete:
            - ls -l "$res_ionic_app_repo_resourcePath/node/client"
            - printenv

      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-virtual
          inputSteps:
            - name: build_ionic_app
          integrations:
            - name: this_artifactory